- include_tasks: apt.yml
- include_tasks: aleph.yml
  when: "env == 'staging' or 'mockturtle' in group_names"
- include_tasks: hmadison.yml
  when: "env == 'staging' or 'mockturtle' in group_names"
- include_tasks: pushcx.yml
