- include: apt.yml
  when: "'{{ family }}' == 'debian'"
- include: yum.yml
  when: "'{{ family }}' == 'redhat'"

- name: copy up unicorn config
  copy: >
    src="unicorn.conf.rb"
    dest="/srv/lobste.rs/http/config"
    owner=lobsters
    group=lobsters
    mode="0644"
