- include_tasks: apt.yml
  when: "'{{ family }}' == 'debian'"
- include_tasks: yum.yml
  when: "'{{ family }}' == 'redhat'"

- name: mariadb config files
  copy:
    src: mysql
    dest: /etc/
    owner: root
    group: root
    mode: 0644

- name: Enable mariadb at startup
  systemd:
    name: mysql
    enabled: yes
