- include_tasks: apt.yml
  when: "'{{ ansible_os_family }}' == 'Debian'"
- include_tasks: yum.yml
  when: "'{{ ansible_os_family }}' == 'RedHat'"

- name: mariadb config files
  register: mariadb_config
  copy:
    src: mysql
    dest: /etc/
    owner: root
    group: root
    mode: '0644'

- name: debian-start permission
  file:
    path: /etc/mysql/debian-start
    mode: u=rwx,g=rx,o=rx

- name: Use new config
  when: mariadb_config.changed
  systemd:
    name: mysql
    state: reloaded

- name: Enable mariadb at startup
  systemd:
    name: mysql
    enabled: yes
