- include_tasks: apt.yml
  when: "'{{ family }}' == 'debian'"
- include_tasks: yum.yml
  when: "'{{ family }}' == 'redhat'"

- name: mariadb config files
  register: mariadb_config
  copy:
    src: mysql
    dest: /etc/
    owner: root
    group: root
    mode: '0644'

- name: Use new config
  when: mariadb_config.changed
  systemd:
    name: mysql
    state: reloaded

- name: Enable mariadb at startup
  systemd:
    name: mysql
    enabled: yes
